name: Swift

on:
  push:
    branches: [ "master" ]

jobs:
  ci:
    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v3
      with:
        xcode-version: '13.4'
    - name: Tuist Setup
      run: make setup
      
    - name: project Generate
      run: |
        rm -rf .package.resolved
        make generate
        
    - name: All Scheme Test
      run: |
        make test
